/*

	URI Hydrobotics
	AVOE motors translation header file

	drivers for motors are included and converted to motor_t types to be used by vehicle_t

	this file is to be hardcoded or generated by auto-tool
*/
