/*

	URI Hydrobotics
	AVOE sensors translation header file

	drivers for sensors are included and converted to sensor_t types to be used by vehicle_t

	this file is to be hardcoded or generated by auto-tool

*/
