/*

	URI Hydrobotics
	AVOE sensors translation header file

	drivers for sensors are included and converted to sensor_t types to be used by vehicle_t

	this file is to be hardcoded or generated by auto-tool

*/


/* tardigrade example */

sensor_t tardigrade_sensors[4];


void setupSensors(){
	tardigrade_sensors[0].init("BNO055", "Adafruit", "I2C", "IMU");
	tardigrade_sensors[1].init("Bar 30m", "BlueRobotics", "I2C", "pressure");
	tardigrade_sensors[2].init("SOS Leak", "BlueRobotics", "GPIO", "leak");
}


