/*

	URI Hydrobotics
	AVOE sensors translation header file

	drivers for sensors are included and converted to sensor_t types to be used by vehicle_t

	this file is to be hardcoded or generated by auto-tool

*/


/* tardigrade example */
// include sensors

#include <ctime>
#include "sensor.h"
#include "motor.h"
#include "vehicle.h"


#include "../plugins/drivers/sensors/imu-dummy/driver.h"
#include "../plugins/middleware/general-sensor/imu.h"




/* raw drivers */
Dummy_BNO055 dummy_imu;



/* AVOE motors */
//bph, bsh, sh, y, ps, ss

motor_t thruster_BPH(1);
motor_t thruster_BSH(1);
motor_t thruster_SH(1);
motor_t thruster_Y(1);
motor_t thruster_PS(1);
motor_t thruster_SS(1);

/* AVOE sensors */
vehicle_t tardigrade("Tardigrade", "2", "AUV");
sensor_t imu(8); 	
sensor_t pressure(4);
sensor_t leak(1);

void tardigrade_setup_sensors(){


	vector_t dummyPosition(0.0, 0.0, 0.0);
	/* AVOE init */
	imu.init("BNO055 dummy", "Adafruit", "I2C", "IMU", dummyPosition);
	pressure.init("Bar 30m", "BlueRobotics", "I2C", "pressure", dummyPosition);
	leak.init("SOS Leak", "BlueRobotics", "GPIO", "leak", dummyPosition);
	
	tardigrade.addSensor(&imu);	
	tardigrade.addSensor(&pressure);
	tardigrade.addSensor(&leak);
	
	/* raw driver init */	
	srand(time(NULL));


}

void tardigrade_setup_motors(){

	vector_t BPH_pos(0.0, 0.0, 0.0);
	vector_t BPH_dir(1.0, 1.0, 1.0);
	thruster_BPH.init("BPH", "T200", "BlueRobotics", "PWM", "Thruster", BPH_pos, BPH_dir);
	
	tardigrade.addMotor(&thruster_BPH);
	//thruster_BPH.print();


}



void tardigrade_update_sensors(){

	/* dummy imu */
	//get temp
	double temp = dummy_imu.get_temperature();
	sensor_set_imu_TEMPERATURE(&imu, temp);


}






