/*

	URI Hydrobotics
	AVOE sensors translation header file

	drivers for sensors are included and converted to sensor_t types to be used by vehicle_t

	this file is to be hardcoded or generated by auto-tool

*/


/* tardigrade example */
// include sensors

#include <ctime>
#include "sensor.h"
#include "motor.h"
#include "vehicle.h"

// INCLUDE MIDDLEWARE

#include "../plugins/middleware/general-sensor/imu.h"
#include "../plugins/middleware/general-sensor/leak.h"
#include "../plugins/middleware/general-sensor/pressure.h"


// INCLUDE DUMMY DRIVERS
#include "../plugins/drivers/sensors/imu-dummy/driver.h"
#include "../plugins/drivers/sensors/pressure-sensor-dummy/driver.h"
#include "../plugins/drivers/sensors/leak-sensor-dummy/driver.h"


// INCLUDE OTHER PLUGINS
#include "../plugins/controllers/tardigrade_basic/controller.h"
//#include "../plugins/drivers/sensors/adafruit_bno055/tools/restore_offsets/restore_offsets.h" //restore_offsets for imu


// INCLUDE REAL DRIVERS
#ifdef TARGET_TARDIGRADE
#include "../plugins/drivers/sensors/bar30m/driver.h"
#include "../plugins/drivers/sensors/bnO055/driver.h"
#include "../plugins/drivers/motors/ppsti/driver.h"
#include "../plugins/middleware/general-motor/ppsti_middleware/motor_mw.h" //andrew's middleware for ppsti
#endif


// DEVICE SETUP
// virtual drivers
Dummy_BNO055 dummy_imu;
pressure_driver dummy_pressure;
leak_sensor dummy_leak;


// real drivers
#ifdef TARGET_TARDIGRADE
BNO055 real_imu;
MS5837 real_pressure;
#endif


// controllers
tardigrade_basic_controller_t controller;


// AVOE MOTORS
//bph, bsh, sh, y, ps, ss

motor_t thruster_BPH(1);
motor_t thruster_BSH(1);
motor_t thruster_SH(1);
motor_t thruster_Y(1);
motor_t thruster_PS(1);
motor_t thruster_SS(1);

// AVOE SENSORS
vehicle_t tardigrade("Tardigrade", "2", "AUV");
sensor_t tardigrade_imu(8); 	
sensor_t tardigrade_pressure(4);
sensor_t tardigrade_leak(1);

// REAL TARDIGRADE TARGET

#ifdef TARGET_TARDIGRADE
void tardigrade_setup_physical(){


	vector_t dummyPosition(0.0, 0.0, 0.0);
 	//AVOE init
	tardigrade_imu.init("BNO055_dummy", "Adafruit", "I2C", "IMU", dummyPosition, dummyPosition);
	tardigrade_pressure.init("Bar_30m", "BlueRobotics", "I2C", "pressure", dummyPosition, dummyPosition);
	tardigrade_leak.init("SOS_Leak", "BlueRobotics", "GPIO", "leak", dummyPosition, dummyPosition);
	
	tardigrade.addSensor(&tardigrade_imu);	
	tardigrade.addSensor(&tardigrade_pressure);
	tardigrade.addSensor(&tardigrade_leak);
	//raw driver init	
	srand(time(NULL));
	real_imu.cold_init(IMU_OFFSETS_FILENAME);
	real_pressure.fullInit();
	std::cout << "Phsyical Sensors Setup\n";

	vector_t BPH_pos(0.0, 0.0, 0.0);
	vector_t BPH_dir(1.0, 1.0, 1.0);
	thruster_BPH.init("BPH", "T200", "BlueRobotics", "PWM", "Thruster", BPH_pos, BPH_dir);
	thruster_BSH.init("BSH", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_SH.init("SH", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_Y.init("Y", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_PS.init("PS", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_SS.init("SS", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);

	// ADD THRUSTERS TO TARDIGRADE
	// order matters depending on controller
	tardigrade.addMotor(&thruster_SH);
	tardigrade.addMotor(&thruster_BSH);
	tardigrade.addMotor(&thruster_BPH);
	tardigrade.addMotor(&thruster_Y);
	tardigrade.addMotor(&thruster_SS);
	tardigrade.addMotor(&thruster_PS);

	controller.init("tardigrade_contoller", &tardigrade);

	// INIT THRUSTERS (this should be better)

	std::vector<int> zero_vector = {1500,1500,1500,1500,1500,1500};
	avoe_ppsti::sendAndReceive (avoe_ppsti::encodeToCommand(zero_vector),"/dev/ttyACM0");	

	



}



void tardigrade_update_sensors_physical(){

	// IMU
	imu::Vector<3> aoe = real_imu.get_Euler_Orientation();
	sensor_set_imu_ABSOULUTE_ORIENTATION_EULER(&tardigrade_imu, aoe.x(), aoe.y(), aoe.z());

	imu::Vector<3> v = real_imu.get_Acceleration_Vector();
	sensor_set_imu_VELOCITY(&tardigrade_imu, v.x(), v.y(), v.z());


	imu::Quaternion aoq = real_imu.get_Quaterion_Orientation();
	sensor_set_imu_ABSOLUTE_ORIENTAION_QUATERNION(&tardigrade_imu, aoq.x(), aoq.y(), aoq.z());

	imu::Vector<3> av = real_imu.get_Angular_Velocity();
	sensor_set_imu_ANGULAR_VELOCITY(&tardigrade_imu, av.x(), av.y(), av.z());

	imu::Vector<3> g = real_imu.get_Gravity_Vector();
	sensor_set_imu_GRAVITY(&tardigrade_imu, g.x(), g.y(), g.z());

	imu::Vector<3> la = real_imu.get_Linear_Acceleration();
	sensor_set_imu_LINEAR_ACCELERATION(&tardigrade_imu, la.x(), la.y(), la.z());

	imu::Vector<3> mfs = real_imu.get_Magnetic_Field_Strength();
	sensor_set_imu_MAGNETIC_FIELD_STRENGTH(&tardigrade_imu, mfs.x(), mfs.y(), mfs.z());

	double temp = real_imu.get_temperature();
	sensor_set_imu_TEMPERATURE(&tardigrade_imu, temp);

	real_pressure.read();
	

	sensor_set_pres_set_altitude(&tardigrade_pressure, real_pressure.getAltitude());
	sensor_set_pres_set_depth(&tardigrade_pressure, real_pressure.getDepth());
	sensor_set_pres_set_pressure(&tardigrade_pressure, real_pressure.getPressure());
	sensor_set_pres_set_temperature(&tardigrade_pressure, real_pressure.getTemperature());



	// UPDATE THRUSTERS
	//set_ppsti_data(&thruster_BPH, &thruster_BSH, &thruster_SH, &thruster_Y, &thruster_PS, &thruster_SS);


};

#endif


// VIRTUAL TARDIGRADE TARGET

void tardigrade_setup_virtual(){

	srand(time(NULL)); // random seed

	vector_t dummyPosition(0.0, 0.0, 0.0);


	// INIT SENSORS
	tardigrade_imu.init("BNO055_dummy", "Adafruit", "I2C", "IMU", dummyPosition, dummyPosition);
	tardigrade_pressure.init("Bar_30m", "BlueRobotics", "I2C", "pressure", dummyPosition, dummyPosition);
	tardigrade_leak.init("SOS_Leak", "BlueRobotics", "GPIO", "leak", dummyPosition, dummyPosition);
	
	// ADD SENSORS TO TARDIGRADE
	tardigrade.addSensor(&tardigrade_imu);	
	tardigrade.addSensor(&tardigrade_pressure);
	tardigrade.addSensor(&tardigrade_leak);
	
	// INIT MOTORS
	vector_t BPH_pos(0.0, 0.0, 0.0);
	vector_t BPH_dir(1.0, 1.0, 1.0);
	thruster_BPH.init("BPH", "T200", "BlueRobotics", "PWM", "Thruster", BPH_pos, BPH_dir);
	thruster_BPH.init("BPH", "T200", "BlueRobotics", "PWM", "Thruster", BPH_pos, BPH_dir);
	thruster_BSH.init("BSH", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_SH.init("SH", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_Y.init("Y", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_PS.init("PS", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);
	thruster_SS.init("SS", "T200", "BlueRobotics", "PWM", "Thruster", dummyPosition, dummyPosition);


	// ADD THRUSTERS TO TARDIGRADE
	// order matters depending on controller
	tardigrade.addMotor(&thruster_SH);
	tardigrade.addMotor(&thruster_BSH);
	tardigrade.addMotor(&thruster_BPH);
	tardigrade.addMotor(&thruster_Y);
	tardigrade.addMotor(&thruster_SS);
	tardigrade.addMotor(&thruster_PS);

	controller.init("tardigrade_contoller", &tardigrade);
}



void tardigrade_update_sensors_dummy(){


	// IMU
	double temp = dummy_imu.get_temperature();
	sensor_set_imu_TEMPERATURE(&tardigrade_imu, temp);

	vector_t aoe = dummy_imu.get_Euler_Orientation();
	sensor_set_imu_ABSOULUTE_ORIENTATION_EULER(&tardigrade_imu, aoe.x, aoe.y, aoe.z);

	vector_t v = dummy_imu.get_Acceleration_Vector();
	sensor_set_imu_VELOCITY(&tardigrade_imu, v.x, v.y, v.z);


	vector4_t aoq = dummy_imu.get_Quaterion_Orientation();
	sensor_set_imu_ABSOLUTE_ORIENTAION_QUATERNION(&tardigrade_imu, aoq.x, aoq.y, aoq.z);

	vector_t av = dummy_imu.get_Angular_Velocity();
	sensor_set_imu_ANGULAR_VELOCITY(&tardigrade_imu, av.x, av.y, av.z);

	vector_t g = dummy_imu.get_Gravity_Vector();
	sensor_set_imu_GRAVITY(&tardigrade_imu, g.x, g.y, g.z);

	vector_t la = dummy_imu.get_Linear_Acceleration();
	sensor_set_imu_LINEAR_ACCELERATION(&tardigrade_imu, la.x, la.y, la.z);

	vector_t mfs = dummy_imu.get_Magnetic_Field_Strength();
	sensor_set_imu_MAGNETIC_FIELD_STRENGTH(&tardigrade_imu, mfs.x, mfs.y, mfs.z);

	//PRESSURE


	sensor_set_pres_set_altitude(&tardigrade_pressure, dummy_pressure.getAltitude());
	sensor_set_pres_set_depth(&tardigrade_pressure, dummy_pressure.getDepth());
	sensor_set_pres_set_pressure(&tardigrade_pressure, dummy_pressure.getPressure());
	sensor_set_pres_set_temperature(&tardigrade_pressure, dummy_pressure.getTemperature());
	
	//LEAK
	setLEAK_STATUS(&tardigrade_leak, dummy_leak.probe());


}

